In [2]:
# ! pip install pandas

import pandas as pd
import numpy as np

print(pd.__version__)

2.0.1


In [4]:
## list

a = [1, 2, 4, 5]
a[1:3]
print(a)
## 
b = [[1, 3, 4],
     [2, 2, 6]]
print(b)

print([b[0][0], b[0][2]])

##
c = [10, 'apple', True]
print(c)

np.array(c)

[1, 2, 4, 5]
[[1, 3, 4], [2, 2, 6]]
[1, 4]
[10, 'apple', True]


array(['10', 'apple', 'True'], dtype='<U11')

In [5]:
## numpy

a = np.array([0, 1, 2, 3, 4])
print("a = ", a)
print(type(a))
# print(a.dtype)

print(a[2:])

## attribute
print("a.shape = ", a.shape)
print("dtype", a.dtype)


a =  [0 1 2 3 4]
<class 'numpy.ndarray'>
[2 3 4]
a.shape =  (5,)
dtype int32


In [31]:
# print(list(range(1, 6)))

array = np.array([range(i, i+2) for i in [1, 4, 7]])
print(array)

print(array.shape)
print(array.dtype)

[[1 2]
 [4 5]
 [7 8]]
(3, 2)
int32


In [34]:
a = np.array([0, 1])       # 벡터
b = np.array([[0, 1]])     # 메트릭스

print(a.shape)
print(b.shape)

(2,)
(1, 2)


In [40]:
##
print(np.eye(3, 5))

print(np.identity(3))
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [43]:
##
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
np.ones((3, 5))
np.ones((3, 5)) * 100

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [49]:
np.full((5, 4), 4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [51]:
np.array([[1, 2],
          [3, 4]])

array([[1, 2],
       [3, 4]])

In [55]:
## range

print(list(range(1, 8, 2)))


print(np.arange(1, 8, 2))

[1, 3, 5, 7]
[1 3 5 7]


In [16]:
# A = np.A([[1, 3, 5, 7, 9],
#                  [3, 5, 7, 9, 11]], dtype = np.int64)

A1 = np.arange(1, 10, 2)
A2 = np.arange(3, 12, 2)
A = np.array([A1, A2], np.int64)

print(A)
print("shape = ", A.shape)
print("dtype = ", A.dtype)



[[ 1  3  5  7  9]
 [ 3  5  7  9 11]]
shape =  (2, 5)
dtype =  int64


In [90]:
I = np.identity(5, np.int64)*2

print(I)
print("shape = ", I.shape)
print("dtype = ", I.dtype)

[[2 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 2 0]
 [0 0 0 0 2]]
shape =  (5, 5)
dtype =  int64


In [96]:
arr = np.arange(12)
arr_3by4 = arr.reshape(3, 4)   # reshape : 데이터를 *by*으로 바꾼다.
arr_by3 = arr.reshape(-1, 3)   # -1 : 뒤에가 맞으면 앞에는 알아서 만드세요.


print(arr)
print()
print(arr_3by4)
print()
print(arr_by3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [100]:
print(arr_by3)
print(list(arr_by3.flat))

print(arr_by3.T)        # .T: 열과 행을 바꿈 


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [17]:
X = np.array([[[0], [1], [2]]])
print('X = \n', X)
print(X.shape)

print(X.reshape(1, 1, 3))
print(X.reshape(3, 1, 1))




X = 
 [[[0]
  [1]
  [2]]]
(1, 3, 1)
[[[0 1 2]]]
[[[0]]

 [[1]]

 [[2]]]


In [42]:
print(X)
print(X.shape)

X.squeeze().shape
print()
print(X.squeeze(axis=0).shape)
print(X.squeeze(axis=0))
print()
print(X.squeeze(axis=2).shape)
print(X.squeeze(axis=2))

[[[0]
  [1]
  [2]]]
(1, 3, 1)

(3, 1)
[[0]
 [1]
 [2]]

(1, 3)
[[0 1 2]]


In [50]:
## vstack
a = np.array([1, 2, 3])
b = np.array([3, 5, 1])
c = np.array([1, 2, 1])

# print(a, b, c)
d = np.vstack([a, b, c])
print(d)


[[1 2 3]
 [3 5 1]
 [1 2 1]]


In [55]:
a = np.array([1, 2, 3])
b = np.array([3, 5, 1])

np.hstack([a, b])

array([1, 2, 3, 3, 5, 1])

In [64]:
a = np.arange(1, 6)
b = np.arange(2, 7)

print(a, b)
print('hstack = \n', np.hstack([a, b]))
print('vstack = \n', np.vstack([a, b]))
print('column_stack = \n', np.column_stack([a, b]))

[1 2 3 4 5] [2 3 4 5 6]
hstack = 
 [1 2 3 4 5 2 3 4 5 6]
vstack = 
 [[1 2 3 4 5]
 [2 3 4 5 6]]
column_stack = 
 [[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]]


In [77]:
A = [[1, 2, 3, 4],
     [2, 4, 5, 8]]

B = [6, 6, 5, 4]


print(np.vstack([A, B]).T)

[[1 2 6]
 [2 4 6]
 [3 5 5]
 [4 8 4]]


In [82]:
## Random samling

## Uniform (균일분포), integer uniform, Gaussian 분포 (정규분포)


## Uniform

print(np.random.rand(5))
print()
print(np.random.rand(3, 5))

[0.11604937 0.10861796 0.16730686 0.77684286 0.15769854]

[[0.40485548 0.8001514  0.00313561 0.28233012 0.16028119]
 [0.67431834 0.25140625 0.89843829 0.7183346  0.63547612]
 [0.61809953 0.14148147 0.35688218 0.74518387 0.69700435]]


In [89]:
print(np.random.randint(1, 10, 10))
print(np.random.randint(1, 10, (3, 2)))

[2 6 6 8 7 9 7 5 7 3]
[[9 8]
 [1 1]
 [8 5]]


In [284]:
# print(np.random.randn(100))  
print(np.random.normal(172, 1, (3, 3)))  # 172 기준으로 1 만큼 랜덤값

[[169.96796232 171.18995403 172.29739344]
 [173.25809478 171.44170952 172.5468607 ]
 [170.39610156 171.74138374 170.55487412]]


In [294]:
a = np.random.normal(10, 1, 10)

print(a)
print(a.mean())
print(np.median(a))

[10.3155626  11.06950015  9.03636207 10.12774556 10.18911699 10.27910314
  9.36641113 10.80878135  8.97004969  9.60268807]
9.976532075020678
10.158431277624942


In [298]:
a = np.array([[1, 2], [3, 4]])

print(a)
print(np.mean(a))
print(np.mean(a, axis= 0))
print(np.mean(a, axis= 1))

[[1 2]
 [3 4]]
2.5
[2. 3.]
[1.5 3.5]


In [302]:
print(np.var(a))
print(np.std(a))
print(np.mean(a))
print(np.max(a))

1.25
1.118033988749895
2.5
4


In [7]:


a = np.array([1, 2, 3, 4])
b = np.array([4, 5, 6, 7])
c = np.array([3, 2, 1, 0])

A = np.vstack([a, b, c])

print(A)
print(A.shape)
print(A.dtype)


[[1 2 3 4]
 [4 5 6 7]
 [3 2 1 0]]
(3, 4)
int32


In [16]:
## indexing 
print(A[0])     # 0번째 row만 출력
print(A[2])     # 2번째 row만 출력
print()

## column indexing
print(A[:, 0])  # 0번째 column만 출력
print(A[:, 3])  # 3번째 column만 출력
print()

## row and column indexing
print(A[0:2, 1:])
print()

## Fancy indexing
print(A[[0, 2], [1, 3]])    # 0, 1 과 2,3을 추출



[1 2 3 4]
[3 2 1 0]

[1 4 3]
[4 7 0]

[[2 3 4]
 [5 6 7]]

[2 0]
